spring:
  application:
    name: bloghub-gw
  cloud:
    gateway:
      routes:
        - id: bloghub-service
          uri: lb://BLOGHUB-SERVICE
          predicates:
            - Path=/api/v1/blogs/**
        - id: bloghub-user-service
          uri: lb://BLOGHUB-USER-SERVICE
          predicates:
            - Path=/api/v1/users
        - id: bloghub-email-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/emails

server:
  port: 9090


