
version: "3"
services:
  pgvector:
    container_name: pgvector1
    logging:
      driver: json-file
    restart: no
    ports:
      - 0.0.0.0:55000:5432/tcp
    network_mode: bridge
    hostname: ef1d1c1332db
    expose:
      - 5432/tcp
      - 55000/tcp
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/15/bin
      - GOSU_VERSION=1.16
      - LANG=en_US.utf8
      - PG_MAJOR=15
      - PG_VERSION=15.4-2.pgdg120+1
      - PGDATA=/var/lib/postgresql/data
    tty: true
    stdin_open: true
    entrypoint:
      - docker-entrypoint.sh
    image: ankane/pgvector:latest
    command: postgres