# 1. bloghub-email-service MongoDB bağlayın.
spring:
  data:
    mongodb:
      username: root
      password: secret
      host: localhost
      port: 27017
      database: admin
# 1. bloghub-email-service MongoDB bağlayın.

